services:
  stock_ai_agent:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: stock_ai_agent
    volumes:
      - ./workspace:/app
      - ./shared_data:/app/data       
    stdin_open: true
    tty: true